/**
 * The generic code generator: an authenticated ProAbono call, in the project's own language.
 *
 * It exists for the journeys no task-specific generator covers. What it must never become is a
 * second, weaker version of those generators -- `install_customer_portal`, `generate_pricing_table`
 * and `sync_usage_rights` each carry rules a generic generator cannot know, and they stay. So this
 * module generates the part that is the same everywhere and is where integrations actually go
 * wrong:
 *
 *  - **Basic auth read from configuration**, Agent key as username, API key as password, never
 *    inlined -- the guardrail of spec section 8, and the one a hand-written snippet breaks first.
 *  - **The Segment carried on every operation that declares it.** Omitted, ProAbono answers for the
 *    Business's default Segment with no error at all, and a `ReferenceCustomer` is unique per
 *    Segment. `/v1/Usages` is the single exception, and it is an exception *in the contract*.
 *  - **Collections read to `TotalItems`**, never one page, and `204 No Content` read as an empty
 *    collection rather than parsed.
 *  - **The customer reference from the session**, never from the request.
 *
 * Everything it says about an operation comes from the contract, at generation time. Nothing here
 * remembers an endpoint.
 */
import type { Stack } from "./hosted-pages.js";

/** How a free-text `language` maps onto the stacks this server generates for. */
const LANGUAGE_ALIASES: Record<string, Stack> = {
  javascript: "node-express",
  js: "node-express",
  node: "node-express",
  "node.js": "node-express",
  nodejs: "node-express",
  typescript: "node-express",
  ts: "node-express",
  express: "node-express",
  next: "next",
  "next.js": "next",
  nextjs: "next",
  react: "next",
  php: "php",
  laravel: "php",
  symfony: "php",
  wordpress: "php",
  python: "python",
  py: "python",
  django: "python",
  flask: "python",
  fastapi: "python",
  ruby: "ruby",
  rails: "ruby",
  "ruby on rails": "ruby",
  csharp: "csharp",
  "c#": "csharp",
  dotnet: "csharp",
  ".net": "csharp",
  aspnet: "csharp",
  "asp.net": "csharp",
};

/**
 * Resolves a language name to a stack, or reports that it could not.
 *
 * An unrecognised language is answered with the generic sketch **and told so**, rather than
 * silently generating JavaScript for a Go project. The HTTP calls themselves are
 * language-independent and are what the generic answer carries.
 */
export function resolveLanguage(language: string): { stack: Stack; recognised: boolean } {
  const key = language.trim().toLowerCase();
  const stack = LANGUAGE_ALIASES[key];
  return stack === undefined ? { stack: "generic", recognised: false } : { stack, recognised: true };
}

/** The guardrails every generated line has to satisfy, whatever the task. */
export const GENERATED_CODE_GUARDRAILS: readonly string[] = [
  "No secret is inlined. Every credential is read from the environment by name — `PROABONO_AGENT_KEY`, `PROABONO_API_KEY`, `PROABONO_PORTAL_SECRET`, `PROABONO_WEBHOOK_SECRET`.",
  "The customer reference comes from the session, never from a URL parameter, a form field or anything else the visitor controls.",
  "The Segment is passed on every operation that declares it. Omitting it does not fail — it silently acts on the Business's default Segment, and a `ReferenceCustomer` is unique per Segment.",
  "The portal security hash is computed server-side, in lowercase hex, per render, and never cached across users.",
  "A billable change is quoted and confirmed with the **end customer** before it is applied. That confirmation is mandatory; the one this server does not ask is the developer's.",
  "Collections are read to `TotalItems`. One page looks exactly like the whole set.",
  "`204 No Content` is an empty collection, not a malformed answer: there is no body to parse.",
];

/** The authenticated client: the part every task needs, in the idiom of the language. */
export function apiClientSnippet(stack: Stack): string {
  switch (stack) {
    case "node-express":
    case "next":
      return [
        "// proabono.js -- one authenticated client, used by everything below.",
        "const AUTHORIZATION =",
        '  "Basic " +',
        "  Buffer.from(",
        "    `${process.env.PROABONO_AGENT_KEY}:${process.env.PROABONO_API_KEY}`,",
        '    "utf8",',
        '  ).toString("base64");',
        "",
        "export async function proabono(method, path, { query = {}, body } = {}) {",
        "  const url = new URL(`${process.env.PROABONO_API_BASE}${path}`);",
        "",
        "  // The Segment, on every operation that declares one. /v1/Usages is the exception: the",
        "  // contract declares none there, so none is sent -- not a shortcut, the contract.",
        '  if (!path.startsWith("/v1/Usages") && query.ReferenceSegment === undefined) {',
        '    url.searchParams.set("ReferenceSegment", process.env.PROABONO_SEGMENT_REF);',
        "  }",
        "  for (const [name, value] of Object.entries(query)) {",
        "    if (value !== undefined) url.searchParams.set(name, String(value));",
        "  }",
        "",
        "  const response = await fetch(url, {",
        "    method,",
        "    headers: {",
        "      Authorization: AUTHORIZATION,",
        '      Accept: "application/json",',
        '      ...(body === undefined ? {} : { "Content-Type": "application/json" }),',
        "    },",
        "    ...(body === undefined ? {} : { body: JSON.stringify(body) }),",
        "  });",
        "",
        "  if (!response.ok) {",
        "    // ProAbono answers with its own Code, which is what the documentation is indexed on.",
        "    const detail = await response.text();",
        "    throw new Error(`ProAbono ${method} ${path} -> ${response.status}: ${detail}`);",
        "  }",
        "",
        "  // 204 No Content: an empty record or an empty collection. There is no body to parse.",
        "  if (response.status === 204) return undefined;",
        "  return response.json();",
        "}",
        "",
        "// Every collection, read whole. One page is a subset and looks exactly like the whole set.",
        "export async function proabonoList(path, query = {}) {",
        "  const items = [];",
        "  let page = 1;",
        "",
        "  for (;;) {",
        "    const payload = await proabono(\"GET\", path, {",
        "      query: { ...query, Page: page, SizePage: 200 },",
        "    });",
        "    const batch = payload?.Items ?? [];",
        "    items.push(...batch);",
        "",
        "    const total = payload?.TotalItems ?? items.length;",
        "    if (items.length >= total || batch.length === 0) return items;",
        "    page += 1;",
        "  }",
        "}",
      ].join("\n");

    case "php":
      return [
        "<?php",
        "// proabono.php -- one authenticated client, used by everything below.",
        "",
        "function proabono(string $method, string $path, array $query = [], ?array $body = null)",
        "{",
        "    // The Segment, on every operation that declares one. /v1/Usages is the exception:",
        "    // the contract declares none there, so none is sent.",
        "    if (!str_starts_with($path, '/v1/Usages') && !isset($query['ReferenceSegment'])) {",
        "        $query['ReferenceSegment'] = getenv('PROABONO_SEGMENT_REF');",
        "    }",
        "",
        "    $url = getenv('PROABONO_API_BASE') . $path . '?' . http_build_query($query);",
        "    $headers = 'Authorization: Basic ' . base64_encode(",
        "        getenv('PROABONO_AGENT_KEY') . ':' . getenv('PROABONO_API_KEY')",
        "    ) . \"\\r\\nAccept: application/json\\r\\n\";",
        "    if ($body !== null) { $headers .= \"Content-Type: application/json\\r\\n\"; }",
        "",
        "    $context = stream_context_create(['http' => [",
        "        'method'  => $method,",
        "        'header'  => $headers,",
        "        'content' => $body === null ? null : json_encode($body),",
        "    ]]);",
        "",
        "    $raw = file_get_contents($url, false, $context);",
        "    if ($raw === false) { throw new RuntimeException(\"ProAbono $method $path failed\"); }",
        "",
        "    // 204 No Content: an empty record or an empty collection. No body to parse.",
        "    if ($raw === '') { return null; }",
        "",
        "    return json_decode($raw, true);",
        "}",
        "",
        "// Every collection, read whole. One page is a subset.",
        "function proabono_list(string $path, array $query = []): array",
        "{",
        "    $items = [];",
        "    $page = 1;",
        "",
        "    while (true) {",
        "        $payload = proabono('GET', $path, $query + ['Page' => $page, 'SizePage' => 200]);",
        "        $batch = $payload['Items'] ?? [];",
        "        $items = array_merge($items, $batch);",
        "",
        "        $total = $payload['TotalItems'] ?? count($items);",
        "        if (count($items) >= $total || count($batch) === 0) { return $items; }",
        "        $page++;",
        "    }",
        "}",
      ].join("\n");

    case "python":
      return [
        "# proabono.py -- one authenticated client, used by everything below.",
        "",
        "import base64",
        "import json",
        "import os",
        "import urllib.parse",
        "import urllib.request",
        "",
        "",
        "def proabono(method: str, path: str, query: dict | None = None, body: dict | None = None):",
        "    query = dict(query or {})",
        "",
        "    # The Segment, on every operation that declares one. /v1/Usages is the exception: the",
        "    # contract declares none there, so none is sent.",
        '    if not path.startswith("/v1/Usages") and "ReferenceSegment" not in query:',
        '        query["ReferenceSegment"] = os.environ["PROABONO_SEGMENT_REF"]',
        "",
        '    url = os.environ["PROABONO_API_BASE"] + path + "?" + urllib.parse.urlencode(query)',
        '    credentials = f"{os.environ[\'PROABONO_AGENT_KEY\']}:{os.environ[\'PROABONO_API_KEY\']}"',
        "    headers = {",
        '        "Authorization": "Basic " + base64.b64encode(credentials.encode()).decode("ascii"),',
        '        "Accept": "application/json",',
        "    }",
        "    data = None",
        "    if body is not None:",
        '        headers["Content-Type"] = "application/json"',
        "        data = json.dumps(body).encode()",
        "",
        "    request = urllib.request.Request(url, data=data, headers=headers, method=method)",
        "    with urllib.request.urlopen(request, timeout=10) as response:",
        "        # 204 No Content: an empty record or an empty collection. No body to parse.",
        "        if response.status == 204:",
        "            return None",
        "        return json.loads(response.read())",
        "",
        "",
        "def proabono_list(path: str, query: dict | None = None) -> list:",
        '    """Every collection, read whole. One page is a subset."""',
        "    items: list = []",
        "    page = 1",
        "",
        "    while True:",
        '        payload = proabono("GET", path, {**(query or {}), "Page": page, "SizePage": 200})',
        '        batch = (payload or {}).get("Items") or []',
        "        items.extend(batch)",
        "",
        '        total = (payload or {}).get("TotalItems", len(items))',
        "        if len(items) >= total or not batch:",
        "            return items",
        "        page += 1",
        "",
      ].join("\n");

    case "ruby":
      return [
        "# proabono.rb -- one authenticated client, used by everything below.",
        "",
        "require 'json'",
        "require 'net/http'",
        "require 'uri'",
        "",
        "def proabono(method, path, query = {}, body = nil)",
        "  # The Segment, on every operation that declares one. /v1/Usages is the exception: the",
        "  # contract declares none there, so none is sent.",
        "  query = query.dup",
        "  query['ReferenceSegment'] ||= ENV.fetch('PROABONO_SEGMENT_REF') unless path.start_with?('/v1/Usages')",
        "",
        "  uri = URI(\"#{ENV.fetch('PROABONO_API_BASE')}#{path}\")",
        "  uri.query = URI.encode_www_form(query)",
        "",
        "  request = Net::HTTPGenericRequest.new(method, body ? true : false, true, uri)",
        "  request['Authorization'] = 'Basic ' + [\"#{ENV.fetch('PROABONO_AGENT_KEY')}:#{ENV.fetch('PROABONO_API_KEY')}\"].pack('m0')",
        "  request['Accept'] = 'application/json'",
        "  if body",
        "    request['Content-Type'] = 'application/json'",
        "    request.body = JSON.generate(body)",
        "  end",
        "",
        "  response = Net::HTTP.start(uri.hostname, uri.port, use_ssl: true) { |http| http.request(request) }",
        "  raise \"ProAbono #{method} #{path} -> #{response.code}\" unless response.is_a?(Net::HTTPSuccess)",
        "",
        "  # 204 No Content: an empty record or an empty collection. No body to parse.",
        "  return nil if response.body.nil? || response.body.empty?",
        "",
        "  JSON.parse(response.body)",
        "end",
        "",
        "# Every collection, read whole. One page is a subset.",
        "def proabono_list(path, query = {})",
        "  items = []",
        "  page = 1",
        "",
        "  loop do",
        "    payload = proabono('GET', path, query.merge('Page' => page, 'SizePage' => 200))",
        "    batch = payload&.dig('Items') || []",
        "    items.concat(batch)",
        "",
        "    total = payload&.dig('TotalItems') || items.size",
        "    return items if items.size >= total || batch.empty?",
        "",
        "    page += 1",
        "  end",
        "end",
      ].join("\n");

    case "csharp":
      return [
        "// ProAbonoClient.cs -- one authenticated client, used by everything below.",
        "",
        "using System.Net.Http.Headers;",
        "using System.Text;",
        "using System.Text.Json;",
        "",
        "public sealed class ProAbonoClient",
        "{",
        "    private readonly HttpClient _http;",
        "",
        "    public ProAbonoClient(HttpClient http)",
        "    {",
        "        _http = http;",
        "        var credentials = Encoding.UTF8.GetBytes(",
        '            $"{Environment.GetEnvironmentVariable("PROABONO_AGENT_KEY")}:" +',
        '            $"{Environment.GetEnvironmentVariable("PROABONO_API_KEY")}");',
        "        _http.DefaultRequestHeaders.Authorization =",
        '            new AuthenticationHeaderValue("Basic", Convert.ToBase64String(credentials));',
        "    }",
        "",
        "    public async Task<JsonElement?> SendAsync(",
        "        HttpMethod method, string path, IDictionary<string, string>? query = null, object? body = null)",
        "    {",
        "        var parameters = new Dictionary<string, string>(query ?? new Dictionary<string, string>());",
        "",
        "        // The Segment, on every operation that declares one. /v1/Usages is the exception:",
        "        // the contract declares none there, so none is sent.",
        '        if (!path.StartsWith("/v1/Usages") && !parameters.ContainsKey("ReferenceSegment"))',
        '            parameters["ReferenceSegment"] = Environment.GetEnvironmentVariable("PROABONO_SEGMENT_REF")!;',
        "",
        '        var queryString = string.Join("&", parameters.Select(pair =>',
        '            $"{Uri.EscapeDataString(pair.Key)}={Uri.EscapeDataString(pair.Value)}"));',
        '        var baseUrl = Environment.GetEnvironmentVariable("PROABONO_API_BASE");',
        "",
        '        using var request = new HttpRequestMessage(method, $"{baseUrl}{path}?{queryString}");',
        "        if (body is not null)",
        '            request.Content = new StringContent(JsonSerializer.Serialize(body), Encoding.UTF8, "application/json");',
        "",
        "        var response = await _http.SendAsync(request);",
        "        response.EnsureSuccessStatusCode();",
        "",
        "        // 204 No Content: an empty record or an empty collection. No body to parse.",
        "        if (response.StatusCode == System.Net.HttpStatusCode.NoContent) return null;",
        "",
        "        return JsonSerializer.Deserialize<JsonElement>(await response.Content.ReadAsStringAsync());",
        "    }",
        "",
        "    // Every collection, read whole. One page is a subset.",
        "    public async Task<List<JsonElement>> ListAsync(string path, IDictionary<string, string>? query = null)",
        "    {",
        "        var items = new List<JsonElement>();",
        "        var page = 1;",
        "",
        "        while (true)",
        "        {",
        "            var parameters = new Dictionary<string, string>(query ?? new Dictionary<string, string>())",
        "            {",
        '                ["Page"] = page.ToString(),',
        '                ["SizePage"] = "200",',
        "            };",
        "",
        "            var payload = await SendAsync(HttpMethod.Get, path, parameters);",
        "",
        "            // `out var` inside a null-conditional call does not satisfy definite",
        "            // assignment (CS0165), so the null is handled first and the reads are plain.",
        "            var batch = new List<JsonElement>();",
        "            var total = items.Count;",
        "",
        "            if (payload is { } page)",
        "            {",
        '                if (page.TryGetProperty("Items", out var found))',
        "                    batch = found.EnumerateArray().ToList();",
        '                if (page.TryGetProperty("TotalItems", out var reported))',
        "                    total = reported.GetInt32();",
        "            }",
        "",
        "            items.AddRange(batch);",
        "            if (items.Count >= total || batch.Count == 0) return items;",
        "            page++;",
        "        }",
        "    }",
        "}",
      ].join("\n");

    case "generic":
      return [
        "# The authenticated ProAbono call, in whatever language the project uses.",
        "#",
        "# 1. AUTH. HTTP Basic over HTTPS: PROABONO_AGENT_KEY as the username, PROABONO_API_KEY as",
        "#    the password. Read both from configuration; never write either into source.",
        "#",
        "# 2. BASE. PROABONO_API_BASE, which already carries the business identifier.",
        "#",
        "# 3. SEGMENT. Pass ReferenceSegment from PROABONO_SEGMENT_REF on every operation that",
        "#    declares it. Omitting it does NOT fail: ProAbono answers for the Business's default",
        "#    Segment, silently, and a ReferenceCustomer is unique per Segment. /v1/Usages is the",
        "#    one exception -- the contract declares no Segment there, so send none.",
        "#",
        "# 4. PAGINATION. Loop on Page until the accumulated count reaches TotalItems. One page is a",
        "#    subset and looks exactly like the whole set.",
        "#",
        "# 5. EMPTY. 204 No Content means an empty record or an empty collection, with no body at",
        "#    all. Do not parse it; treat it as zero items.",
        "#",
        "# 6. ERRORS. ProAbono returns its own Code alongside the HTTP status. Keep the Code: it is",
        "#    what the documentation and the troubleshooting guide are indexed on.",
      ].join("\n");
  }
}
